version: "3.9"

services:
  enginedb:
    image: postgres:16-alpine
    container_name: engine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5397:5432"
    volumes:
      - engine_data:/var/lib/postgresql/data
    networks:
      - sports-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d engine" ]
      interval: 10s
      retries: 5

  competition-engine:
    build: team_3-CompetitionEngine
    container_name: competition-engine
    restart: on-failure
    depends_on:
      enginedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://enginedb:5432/engine
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - sports-network

volumes:
  engine_data:

networks:
  sports-network:
    driver: bridge
