secrets:
  jwt_secret:
    file: ../secrets/jwt_secret.key

services:
  enginedb:
    image: postgres:16-alpine
    container_name: engine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5397:5432"
    volumes:
      - engine_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d engine" ]
      interval: 1s
      retries: 5
    networks:
      - microservices-net   # ← добавили

  competitionengine:
    build: .
    container_name: competitionengine
    restart: on-failure
    depends_on:
      enginedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://enginedb:5432/engine
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET_PATH: /run/secrets/jwt_secret
      STATISTIC_URL: http://statisticservice:8080
    ports:
      - "8088:8080"
    secrets:
      - jwt_secret
    networks:
      - microservices-net   # ← добавили

volumes:
  engine_data:

networks:
  microservices-net:              # ← перезаписываем standard default
    external: true
